### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by vidavidorra** [vidavidorra/vidavidorra.github.io#1]
- [ ] Fix CONTACT section
- [ ] Add SKILLS section
- [ ] Add RESUME section
- [ ] Remove project template
- [ ] Add ABOUT section
- [ ] Add image for CHANGE LICENSE HEADER section
- [ ] Add image for PIC BOOTLOADER section
- [ ] Switch portfolio section to the right side
